export default [
  {
    id: 'facing-the-interviews-confidently',
    title: 'Facing the Interviews Confidently',
    description: 'Learn how to confidently face job interviews.',
    image: 'interviews.jpg',
    video: '8cPXpUjZODo',
    overview: `Facing interviews confidently is essential for making a positive first impression and standing out among candidates. Confidence in an interview comes from preparation, self-awareness, and clear communication. Understanding the job role, researching the company, and practicing answers to common interview questions can make you feel more in control. It's also important to project calm body language, maintain eye contact, and articulate your thoughts effectively. Confidence doesn’t mean knowing everything—it means demonstrating a willingness to learn and a proactive attitude.`,
    content: [
      `Understanding the importance of interviews`,
      `Preparing for interviews`,
      `Researching the company and the job role`,
      `Practicing answers to common interview questions`,
      `Projecting calm body language and maintaining eye contact`,
      `Articulating your thoughts effectively`,
      `Demonstrating a willingness to learn and a proactive attitude`,
      `Handling difficult questions and situations`,
      `If you’re unsure of an answer, stay composed. It's okay to take a moment to think or to admit you don't know something.`,
      `Pivot towards how you would find the solution or explain how you handle challenges.`,
    ],
    backgroundPosition: 'top',
  },
  {
    id: 'group-discussions-gd',
    title: 'Group Discussions (GD)',
    description: 'Master the art of participating in group discussions.',
    image: 'group-discussion.png',
    video: '8cPXpUjZODo',
    overview: `Group discussions (GDs) are often used to assess a candidate’s ability to communicate, work in a team, and think critically under pressure. Facing group discussions confidently involves being well-prepared, assertive, and actively contributing without dominating. It's essential to listen to others, articulate your ideas clearly, and be respectful of differing opinions. Confidence in a GD is about striking the right balance between assertiveness and collaboration, showcasing leadership qualities, and engaging constructively in the conversation.`,
    content: [
      `Understanding the purpose of group discussions`,
      `Preparing for group discussions`,
      `Researching the topic and forming your opinion`,
      `Listening actively and contributing thoughtfully`,
      `Maintaining a balance between speaking and listening`,
      `Respecting others’ opinions and building on them`,
      `Demonstrating leadership skills and teamwork`,
      `Handling disagreements and conflicts constructively`,
      `If you disagree with someone, express your opinion respectfully and back it up with facts or examples.`,
      `Avoid personal attacks or aggressive behavior. Focus on the issue, not the person.`,
    ],
    backgroundPosition: 'top',
  },
  {
    id: 'curriculum-vitae-cv-writing',
    title: 'Curriculum Vitae (CV) Writing',
    description: 'Learn how to create an impressive CV.',
    image: 'cv-writting.jpg',
    video: '8cPXpUjZODo',
    overview:
      'Writing a strong Curriculum Vitae (CV) is a crucial step in presenting your skills, experiences, and qualifications to potential employers. A well-crafted CV highlights your accomplishments, matches the job requirements, and creates a positive first impression. Confidence in CV writing comes from knowing how to tailor your content to the job you’re applying for, maintaining a professional tone, and ensuring clarity and readability. It’s essential to make your CV concise, focused, and error-free, as this document is often the first gateway to landing an interview.',
    content: [
      `Understanding the purpose of a CV`,
      `Structuring your CV effectively`,
      `Highlighting your skills, experience, and achievements`,
      `Tailoring your CV to the job role and company`,
      `Using clear and concise language`,
      `Formatting your CV for readability`,
      `Proofreading your CV for errors`,
      `If you’re unsure of an answer, stay composed. It's okay to take a moment to think or to admit you don't know something.`,
      `Pivot towards how you would find the solution or explain how you handle challenges.`,
    ],
    backgroundPosition: 'top',
  },
  {
    id: 'campus-to-corporate',
    title: 'Campus to Corporate',
    description:
      'Transition smoothly from campus life to corporate environment.',
    image: 'campus-to-corporate.jpg',
    video: '8cPXpUjZODo',
    overview:
      'The transition from campus to corporate life is a significant shift for many graduates. It requires adapting to new professional environments, expectations, and responsibilities. Confidence in this transition comes from understanding the differences between academic and corporate settings and learning to navigate the workplace with a proactive and growth-oriented mindset. This phase of life offers new opportunities to apply academic knowledge to real-world problems while developing soft skills, such as communication, teamwork, and time management, that are essential for success in any corporate setting.',
    content: [
      `Understanding the differences between campus and corporate life`,
      `Adapting to the corporate culture and environment`,
      `Developing professional communication skills`,
      `Building effective relationships with colleagues`,
      `Managing time and priorities effectively`,
      `Demonstrating a proactive attitude and willingness to learn`,
      `Navigating office politics and conflicts`,
      `If you disagree with someone, express your opinion respectfully and back it up with facts or examples.`,
      `Avoid personal attacks or aggressive behavior. Focus on the issue, not the person.`,
    ],
    backgroundPosition: 'top',
  },
  {
    id: 'communication-skills',
    title: 'Communication Skills',
    description: 'Improve your verbal and written communication skills.',
    image: 'communication-skills.jpg',
    video: '8cPXpUjZODo',
    overview:
      'Communication skills are essential for success in both personal and professional life. Effective communication involves not only conveying information clearly and concisely but also actively listening and understanding others. In the workplace, strong communication skills enable better collaboration, build relationships, and help resolve conflicts. Whether it’s verbal, non-verbal, or written, mastering communication improves your ability to express ideas, share feedback, and engage with diverse audiences, making it a key asset in any environment.',
    content: [
      `Verbal Communication`,
      `Non-Verbal Communication`,
      `Listening Skills`,
      `Presentation Skills`,
      `Public Speaking`,
      `Writing Skills`,
      `Interpersonal Skills`,
      `Negotiation Skills`,
      `Conflict Resolution`,
      `Emotional Intelligence`,
      `Empathy`,
      `Assertiveness`,
      `Feedback and Active Listening`,
      `Networking`,
      `Cross-Cultural Communication`,
      `Communication in the Digital Age`,
    ],
    backgroundPosition: 'top',
  },
  {
    id: 'social-and-corporate-etiquette',
    title: 'Social and Corporate Etiquette',
    description: 'Learn proper etiquette for social and corporate settings.',
    image: 'social-corporate.jpg',
    video: '8cPXpUjZODo',
    overview:
      'Social and corporate etiquette refers to the accepted norms and behaviors that show respect and professionalism in social and workplace settings. In a corporate environment, etiquette includes everything from proper communication, dressing appropriately, and being punctual, to showing respect for colleagues and maintaining a positive attitude. Understanding and practicing good etiquette helps create a harmonious work atmosphere, fosters strong relationships, and enhances your personal brand. It’s an important aspect of making a positive impression and advancing in your professional life.',
    content: [
      `Understanding the importance of etiquette in social and corporate settings`,
      `Dressing appropriately for different occasions`,
      `Greeting and interacting with others respectfully`,
      `Using proper table manners and dining etiquette`,
      `Maintaining professional behavior in the workplace`,
      `Handling social and business introductions gracefully`,
      `Navigating networking events and social gatherings`,
      `If you disagree with someone, express your opinion respectfully and back it up with facts or examples.`,
      `Avoid personal attacks or aggressive behavior. Focus on the issue, not the person.`,
    ],
    backgroundPosition: 'top',
  },
  {
    id: 'written-communication',
    title: 'Written Communication',
    description: 'Enhance your written communication skills.',
    image: 'written-communication.jpg',
    video: '8cPXpUjZODo',
    overview:
      'Written communication is the process of conveying messages and information through written words. It plays a crucial role in the workplace, as it includes emails, reports, proposals, and documentation. Effective written communication is clear, concise, and free from ambiguity, ensuring that the intended message is easily understood. Strong writing skills help improve professionalism, reduce misunderstandings, and enhance collaboration in both formal and informal contexts. Mastering written communication is essential for success in any professional environment.',
    content: [
      `Understanding the importance of written communication`,
      `Writing clear and concise emails`,
      `Crafting effective business letters and reports`,
      `Using proper grammar and punctuation`,
      `Formatting documents for readability`,
      `Proofreading and editing for errors`,
      `If you’re unsure of an answer, stay composed. It's okay to take a moment to think or to admit you don't know something.`,
      `Pivot towards how you would find the solution or explain how you handle challenges.`,
    ],
    backgroundPosition: 'bottom',
  },
  {
    id: 'public-speaking-skills',
    title: 'Public Speaking Skills',
    description: 'Improve your public speaking skills.',
    image: 'public-speaking.jpg',
    video: '8cPXpUjZODo',
    overview:
      'Public speaking skills involve the ability to effectively communicate ideas, information, or messages to an audience in a clear, confident, and engaging manner. These skills are essential for presentations, meetings, or any situation where you need to address a group. Strong public speaking requires good preparation, organization, and the ability to connect with the audience while managing nerves. Mastering this skill boosts confidence, enhances leadership potential, and plays a key role in personal and professional success.',
    content: [
      `Understanding the importance of public speaking`,
      `Overcoming stage fright and nervousness`,
      `Structuring your speech effectively`,
      `Engaging the audience with storytelling and examples`,
      `Using visual aids and props effectively`,
      `Handling questions and feedback confidently`,
      `If you’re unsure of an answer, stay composed. It's okay to take a moment to think or to admit you don't know something.`,
      `Pivot towards how you would find the solution or explain how you handle challenges.`,
    ],
    backgroundPosition: 'center',
  },
  {
    id: 'spoken-english',
    title: 'Spoken English',
    description:
      'Speaking English is no longer a luxury to be enjoyed by a few people in',
    image: 'spoken-english.jpg',
    video: '8cPXpUjZODo',
    overview:
      'Speaking English is no longer a luxury to be enjoyed by a few people in the élite class, but has become a necessity in the backdrop of increased competition, information sharing and enlarged horizon of activities. By learning to speak English confidently, the person can enlarge his vision of thinking, expand his circle of contacts and contribute in an increasing measure to the organization he is working for. Speaking English also makes the person more confident and renders him more relevant and contemporary.',
    content: [
      `To enable employees to speak in English`,
      `To enhance the self-confidence of the employees due to their ability to speak English`,
      `To enable the employees to answer in English the questions asked by visitors, superior executives, Colleagues, etc.,`,
      `To enable the employees to make simple, oral presentations regarding Small Group Activities, Quality Circles, Process Improvements, Cost Effectiveness, etc.,`,
      `To empower the employees to converse in meetings in English`,
      `Spoken English`,
      `Grammar, Structures, Use of appropriate words`,
      `Situational conversation in English`,
      `Vocabulary building`,
      `Proper pronunciation`,
      `Sentence formations`,
      `Basic etiquette in English`,
      `Confidence building through spoken English`,
      `Common errors in Spoken English and how to avoid them`,
    ],
    backgroundPosition: 'top',
  },
  {
    id: 'self-confidence',
    title: 'Self Confidence',
    description: 'Boost your self confidence.',
    image: 'self-confidence.png',
    video: '8cPXpUjZODo',
    overview:
      'Self-confidence is the belief in your abilities, qualities, and judgment. It plays a crucial role in how you approach challenges, interact with others, and pursue goals. A strong sense of self-confidence enables you to take risks, make decisions, and face difficult situations with a positive mindset. It is built through self-awareness, continuous learning, and accepting both strengths and areas for improvement. Cultivating self-confidence helps you overcome obstacles, enhances performance, and contributes to success in both personal and professional life.',
    content: [
      `Understanding self-confidence`,
      `Building self-esteem and self-worth`,
      `Overcoming self-doubt and negative self-talk`,
      `Setting and achieving goals`,
      `Developing a growth mindset`,
      `Practicing self-compassion and self-care`,
      `If you’re unsure of an answer, stay composed. It's okay to take a moment to think or to admit you don't know something.`,
      `Pivot towards how you would find the solution or explain how you handle challenges.`,
    ],
    backgroundPosition: 'top',
  },
  {
    id: 'goal-setting',
    title: 'Goal Setting',
    description: 'Learn how to set and achieve your goals.',
    image: 'goal-setting.jpg',
    video: '8cPXpUjZODo',
    overview:
      'Goal setting is the process of identifying and defining clear, achievable objectives to guide your personal or professional growth. It helps provide direction, motivation, and a sense of purpose by breaking down long-term ambitions into manageable steps. Effective goal setting involves creating specific, measurable, attainable, relevant, and time-bound (SMART) goals. By setting and tracking progress towards these goals, individuals can stay focused, overcome challenges, and achieve success with greater clarity and confidence.',
    content: [
      `Understanding the importance of goal setting`,
      `Setting SMART goals (Specific, Measurable, Achievable, Relevant, Time-bound)`,
      `Creating an action plan to achieve your goals`,
      `Breaking down goals into smaller tasks`,
      `Tracking progress and adjusting as needed`,
      `Staying motivated and focused on your goals`,
      `If you’re unsure of an answer, stay composed. It's okay to take a moment to think or to admit you don't know something.`,
      `Pivot towards how you would find the solution or explain how you handle challenges.`,
    ],
    backgroundPosition: 'center',
  },
  {
    id: 'positive-attitude',
    title: 'Positive Attitude',
    description: 'Develop a positive attitude.',
    image: 'positive-attitude.jpg',
    video: '8cPXpUjZODo',
    overview:
      'A positive attitude is a mental outlook that emphasizes optimism and resilience, focusing on the good in situations rather than the negative. It plays a vital role in shaping behavior, influencing relationships, and enhancing overall well-being. Individuals with a positive attitude are more likely to tackle challenges with enthusiasm, foster collaborative environments, and maintain motivation in the face of adversity. Cultivating a positive attitude can improve mental health, boost productivity, and lead to greater success both personally and professionally.',
    content: [
      `Understanding the power of a positive attitude`,
      `Cultivating optimism and resilience`,
      `Practicing gratitude and mindfulness`,
      `Fostering a growth mindset`,
      `Turning challenges into opportunities`,
      `If you’re unsure of an answer, stay composed. It's okay to take a moment to think or to admit you don't know something.`,
      `Pivot towards how you would find the solution or explain how you handle challenges.`,
    ],
    backgroundPosition: 'center',
  },
  {
    id: 'Non-verbal-communication',
    title: 'Non-verbal Communication',
    description: 'Learn how to communicate effectively without words.',
    image: 'non-verbal-communication.jpg',
    video: '8cPXpUjZODo',
    overview:
      'Non-verbal communication encompasses all the ways we convey messages without words, including body language, facial expressions, gestures, posture, and eye contact. It plays a crucial role in interpersonal interactions, as it can reinforce or contradict verbal messages. Understanding and effectively using non-verbal cues enhances communication, builds rapport, and conveys emotions and intentions. Mastering non-verbal communication skills is essential for successful interactions in both personal and professional contexts.',
    content: [
      `Understanding the importance of non-verbal communication`,
      `Reading body language and facial expressions`,
      `Using gestures and eye contact effectively`,
      `Maintaining good posture and personal space`,
      `Interpreting non-verbal cues from others`,
      `If you’re unsure of an answer, stay composed. It's okay to take a moment to think or to admit you don't know something.`,
      `Pivot towards how you would find the solution or explain how you handle challenges.`,
    ],
    backgroundPosition: 'center',
  },
  {
    id: 'time-management',
    title: 'Time Management',
    description:
      'Time is the most important, yet a very elusive resource. This unique Training Programme has',
    image: 'time-management.png',
    video: '8cPXpUjZODo',
    overview:
      'Time is the most important, yet a very elusive resource. This unique Training Programme has been very thoughtfully formulated to prove that, with innovative time management techniques, one can have enough time to do all that he has been doing(possibly in a better way and in a shorter time) still have time to do lot many things which gives him a sense of satisfaction, achievement and self-worth. This programme shatters the deep rooted myths and changes your paradigm about time management. It helps the participant to make fundamental and notional corrections in the psycho-emotive apparatus of his/her personality enabling him/her to do more in less time with more confidence, with less stress, more effectively and, above all, enjoy he/she is doing.',
    content: [
      `Understanding time as the most important resource`,
      `Basic concepts of time management`,
      `Importance of time – its management`,
      `Rationing of time for ‘Urgent’ and ‘Important’ work`,
      `Identifying and eliminating time wasters`,
      `Planning, organizing, systematizing, simplifying and compounding of work`,
      `Prioritizing and structuring the time`,
      `Goal setting and its relevance in time management`,
      `Tools and techniques for managing time`,
      `Identifying time robbers (time wasters) and techniques to prevent them`,
      `‘Planning’ as a tool for accomplishing goals and avoiding last-minute rush`,
      `Organizing and planning for results`,
      `How do effective communication and good relationships help in aligning one’s thoughts and emotions with others thereby reducing time in communication, relationship, etc`,
      `Simplifying and compounding of jobs for doing ‘more’ in ‘less’ time`,
      `Procrastination and how to avoid it`,
      `Managing time in the meetings`,
      `Delegation`,
      `Distributing time for career, family and self- development; work – life balance`,
      `Time Management and Stress Management`,
    ],
    backgroundPosition: 'center',
  },
  {
    id: 'creativity-and-innovation',
    title: 'Creativity and Innovation',
    description: 'Develop your creativity and innovation skills.',
    image: 'creativity.jpg',
    video: '8cPXpUjZODo',
    overview:
      'Creativity and innovation are the processes of generating new ideas, concepts, or solutions to problems. Creativity involves thinking outside the box and exploring possibilities, while innovation takes those ideas and transforms them into practical applications or improvements. Both are vital for personal growth and organizational success, fostering adaptability and competitiveness in a rapidly changing world. Encouraging a culture of creativity and innovation leads to fresh perspectives, enhanced problem-solving, and the development of groundbreaking products and services.',
    content: [
      `Understanding creativity and innovation`,
      `Fostering a creative mindset`,
      `Generating new ideas and solutions`,
      `Thinking outside the box`,
      `Overcoming creative blocks and barriers`,
      `Encouraging innovation in the workplace`,
      `If you’re unsure of an answer, stay composed. It's okay to take a moment to think or to admit you don't know something.`,
      `Pivot towards how you would find the solution or explain how you handle challenges.`,
    ],
    backgroundPosition: 'center',
  },
  {
    id: 'stress-management',
    title: 'Stress Management',
    description:
      'Stress is a major reason for decreased performance and also for a number of diseases.',
    image: 'stress-management.jpg',
    video: '8cPXpUjZODo',
    overview:
      'Stress is a major reason for decreased performance and also for a number of diseases. A person under stress experiences a host of problems like confused thinking, irritability, lack of concentration and memory power. Most of the stress is self-created and hence is self-curable. This training programme gives effective and practical guidelines to manage stress and perform at the best in the work place.',
    content: [
      `Definition of ‘Stress’`,
      `Identification and symptoms of stress`,
      `Harmful effects of stress on the performance, attitude and health`,
      `Stress inducing factors in an organization`,
      `Stress related diseases`,
      `Practical guidelines to combat stress at workplace`,
      `Stress management and work culture. How to create a stress – free culture by sound interpersonal relations (with superiors, colleagues and sub-ordinates), empathy, collective working, positive attitude and self motivation`,
      `Stress Management techniques – food habits, physical exercises, planning, positive attitude, breathing techniques, cheerfulness, music, socializing, nature watching, relaxation, assertiveness and other life styles to be adopted for management of stress`,
      `Achieving the work – life balance`,
      `Interdependence of time management and stress management`,
      `How to manage stress during working hours and in spare time ?(when you havea few minutes at your disposal)`,
      `Drawing up a concrete action plan for stress management at workplace and family`,
    ],
    backgroundPosition: 'center',
  },
  {
    id: 'academic-excellence',
    title: 'Academic Excellence',
    description: 'Achieve academic excellence.',
    image: 'academic-excellence.jpg',
    video: '8cPXpUjZODo',
    overview:
      'Academic excellence refers to the pursuit of high standards in education, characterized by strong performance, a commitment to learning, and the achievement of outstanding results. It encompasses not only grades but also critical thinking, creativity, and engagement in the learning process. Striving for academic excellence helps develop essential skills, boosts self-confidence, and prepares individuals for future challenges. It encourages lifelong learning and instills a sense of discipline, resilience, and curiosity, all of which are valuable in both academic and professional endeavors.',
    content: [
      `Understanding the importance of academic excellence`,
      `Setting academic goals and objectives`,
      `Developing effective study habits`,
      `Time management for academic success`,
      `Improving memory and concentration`,
      `Overcoming test anxiety and stress`,
      `Seeking help and support when needed`,
      `If you’re unsure of an answer, stay composed. It's okay to take a moment to think or to admit you don't know something.`,
      `Pivot towards how you would find the solution or explain how you handle challenges.`,
    ],
    backgroundPosition: 'center',
  },
];
